### ISSUE TITLE
Other Language Bindings

### ISSUE THREAD

**Issue by sirinath** [elemental/Elemental#109]
Is it possible to add bindings to other languages?

**Comment by poulson** [comment]
Of course. There are already C and Python interfaces, and a fledgling Julia interface; what language were you curious about?

**Comment by sirinath** [comment]
JVM and .net languages

**Comment by poulson** [comment]
Interfacing native libraries with the JVM is certainly possible, but it tends to involve a significant performance penalty due to the Java Native Interface typically involving conversions to and from the native types. Also, the JVM, as far as I am aware, requires 32-bit pointers, and so there would be limitations in the problems that could be solved.

With that said, I believe that there are well-known hacks that allow one to avoid some of the JNI overheads if you can guarantee that the function call executes sufficiently quickly, but I do not ever use Java or the JVM, so there would be better people to ask.
