### ISSUE TITLE
'make' by default installs parmetis and scalapack

### ISSUE THREAD

**Issue by evaleev** [elemental/Elemental#120]
The install location ordinarily should not be polluted until 'make install'

**Comment by poulson** [comment]
For better or for worse, this is standard behavior for CMake's `ExternalProject_Add`: https://cmake.org/cmake/help/v3.0/module/ExternalProject.html

Elemental used to use git submodules, but I then discovered that many GitHub features (e.g., downloading a zip of the project source) are incompatible with submodules, and that a large percentage of users do not read the documentation far enough to run ``git clone --recursive``. For this reason, the decision was made to use CMake external projects instead.

Unless I am missing something, external projects always install during the `make` phase (which is confusing because `sudo` is then, in general, required for both the `make` and `make install` phases). I've documented this in Elemental's build instructions: http://libelemental.org/documentation/dev/build.html#building-elemental

**Comment by justusc** [comment]
We encountered the issue you described. My solution was to disable the install step for external project, and implement an install step myself.

The code we use is:
```cmake
# Since 'install-madness' target cannot be linked to the 'install' target,
# we will do it manually here.
install(CODE
    "
    execute_process(
        COMMAND \"${CMAKE_MAKE_PROGRAM}\" \"install-world\" \"install-clapack\" \"install-common\" ${ELEMENTAL_INSTALL_TARGET}
        WORKING_DIRECTORY \"${MADNESS_BINARY_DIR}\"
        RESULT_VARIABLE error_code)
    if(error_code)
      message(FATAL_ERROR \"Failed to install 'madness'\")
    endif()
    "
    )
```
It would be nice if ExternalProject allowed this kind of flexibility out of the box, but I am not very hopeful.

I think that ExternalProject installs during build so that the resulting binary/libraries/headers/_etc_. are in their final location. This simplifies the installation process for shared libraries since all binaries and libraries, including those of the sub projects, need to be relinked or at least adjust rpaths. In the case of our project, this is a non-issue since it is a header only library. I am not sure what is involved in this process, but I have a feeling it would not be very pretty.

After looking at the solution for other projects, I have recently come to the conclusion that the best automated build solution for CMake projects is to use a super-project that can build project dependencies with ExternalProject. The advantage of this approach, as I see it, is that your main project configure scripts can remain relatively clean (only doing checks), while the complexities of building dependencies can be self contained in a light-weight CMake project.

**Comment by evaleev** [comment]
The blame goes to not only ExternalProject (we avoid it in TiledArray to install MADNESS components) ... cmake only recently started providing support for proper buildtree vs installtree "interfaces" and these are not widely used (i.e. BUILD_INTERFACE INSTALL_INTERFACE generator expressions)

Feel free to close, just wanted to get your perspective whether this is going to be addressed any time soon.

**Comment by poulson** [comment]
I'm still a bit confused as to what you are concretely suggesting, as well as to why it is more than a minor inconvenience for `make` to install dependencies. Are you suggesting not using `ExternalProject_Add`? If so, is there another suggestion?

**Comment by justusc** [comment]
We originally used the same approach you have in Elemental. The main issue with the build process is that it forces building of dependences during the build phase of the main program.  And as you pointed out, this leads to the problem of requiring root privileges to build. Another major inconvenience is that ExternalProject is a too aggressive about downloading dependencies. These issues are fine for a single build and installation, but for development work, it can be a significant interruption to work flow.

My suggestion is to create a super-project that is separate from the Elemental project and handles the logic of building dependencies for Elemental as well as Elemental itself. Basically, the super-project would do a `find_package` for each dependency. If the dependency is not found, build it using ExternalProject. Then pass the appropriate flags to your project. Most of the code for this project could be copied from the current Elemental configure scripts. The advantage to this approach is that it cleanly separates building dependencies from your main code base.

I am working on setting up a super-project for TiledArray, which will include MADNESS and Elemental as dependencies. If it is setup correctly, it can be used as a super-project for any of these projects. I am envisioning a configure script for Elemental that looks like:
```
$ cmake -D PROJECT=Elemental
        -D CMAKE_INSTALL_PREFIX=/path/to/install/everything
        -D SOURCE_DIR=/path/to/elemental/source
        -D BINARY_DIR=/path/to/elemental/build
        ./
```
And for TiledArray (using the same super-project):
```
$ cmake -D PROJECT=TiledArray
        -D CMAKE_INSTALL_PREFIX=/path/to/install/everything
        -D SOURCE_DIR=/path/to/tiledarray/source
        -D BINARY_DIR=/path/to/tiledarray/build
        -D ENABLE_ELEMENTAL=ON
        ./
```
The result would be all of your dependencies built and installed, and the source/build directories for your target project (Elemental/TiledArray/MADNESS) setup for you.

I think it would be ideal if you helped with the elemental specific parts of the project.

**Comment by poulson** [comment]
Thanks for the constructive feedback Justus! That would indeed be nice for several additional reasons, such as some of the fragile steps that I have had to take to "guess" configuration parameters during the configuration phase that are produced by `ExternalProject_Add` during the `make` phase.

Furthermore, having a superproject should allow for more general dependency resolution, such as downloading and installing mpich.

I'm all for this and would be happy to help.

**Comment by evaleev** [comment]
>
> I'm still a bit confused as to what you are concretely suggesting, as well
> as to why it is more than a minor inconvenience for make to install
> dependencies. Are you suggesting not using ExternalProject_Add? If so, is
> there another suggestion?
>
Having to install something in order to build is a major violation. E.g. it
means the package will not be accepted into mainstream package echosystems
(e.g. Debian, Brew, etc.). Based on my experiences those guys are very
picky :) and this will not fly.

I only know superficially what Justus has in mind ... the major problem I
see is that until the packages in a super-project properly declare their
cmake interface details for use from the build tree and from the install
tree these details will have to be managed by someone, e.g. by the writer
of the superpackage. This is where most work will be for SciBuilder.

**Comment by poulson** [comment]
@evaleev I definitely agree that an RPM would not do this, but the external projects shouldn't (ideally) be needed if the existence of a package manager is assumed. (By "ideally", I mean that, if one is working on integrating Elemental into a package manager, ideally one would also have worked to ensure that any custom updates to the dependencies (i.e., ParMETIS and ScaLAPACK) are packaged first).

But I am sold on Justus's proposal. The current CMake code for handling nested `ExternalProject_Add` commands for the chain Elemental -> ScaLAPACK -> {OpenBLAS,BLIS,etc.} is disgustingly fragile and I would love to replace it with a superproject that one first executes to handle all dependencies (the obvious weakness being that one no longer has a single `configure`/`make`/`make install` sequence).

Ideally the superproject could handle:
1. Installing/bootstrapping CMake
2. Installing/detecting MPICH, OpenMPI, or MVAPICH
3. Installing/detecting BLAS and LAPACK libraries (and perhaps also `libflame`)
4. Installing/detecting either ParMETIS or METIS
5. Optionally installing/detecting MPFR and MPC
6. Optionally installing/detecting ScaLAPACK

Elemental already contains several CMake scripts which should greatly ease this process in the `cmake/` folder.

**Comment by evaleev** [comment]
@justusc your idea for SciBuilder is to install packages
