### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [elemental/Elemental#121]
Would you like to [replace any double quotes](https://github.com/elemental/Elemental/blob/134a7b24f4fe76ef30293305055f363fdeb8e47e/include/El.hpp#L13 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by justusc** [comment]
The angle brackets are supposed to be used for standard system files. Though there is nothing to stop one from using angle brackets, I believe the general guidance is to use double quotes for everything other than standard system files. Furthermore, it is recommended to use relative paths with double quotes (since the directory of the file is the first one searched) to avoid conflicts with other libraries.

Given these guidelines, the El.hpp file is correct. Perhaps a better recommendation would be to change include directive for the rest of Elemental to use relative paths, if there is a conflict with other packages. But I would not recommend such a change without a driving need.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by jeffhammond** [comment]
Unless there is an actual bug associated with this issue, it should be closed as [bikeshedding](https://en.wikipedia.org/wiki/Parkinson%27s_law_of_triviality).

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?

**Comment by justusc** [comment]
> Unless there is an actual bug associated with this issue, it should be closed as bike shedding.

Agreed. 

>Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?

Unless you measure your compile times in hours or days, file search time is trivial.

> * How do you think about to avoid "a duplicated file search" here?
> * Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?

There is no duplicate file search. This just means searches look like:

* `#include "..."`
  1. Search current directory of the file
  2. Search paths specified by `#include <...>`

* `#include <...>`
  1. Search paths specified in command-line arguments, i.e. path specified with `-I`
  2. Search system directories

In terms of performance (time to find a file), if double quotes and relative paths are used in Elemental, as the current directory of the file is the first one searched.

> There are different opinions about the handling of the involved implementation-defined behavior.

Keep in mind, this is all compiler specific. You are free to use whatever options you prefer for your compiler, but Elemental should to remain portable/general.

Again, I do not recommend changing anything without a driving need.

**Comment by elfring** [comment]
I would generally prefer to exclude the potential for the inclusion of header files from unexpected directories. Can such a security detail become a bit more important occasionally?

**Comment by jeffhammond** [comment]
@elfring Can you explain your motivation for all of this?  Are you an Elemental user or developer?  What is your long-term goal with Elemental?

I think the potential security issues with inclusion of header files from unexpected directories is well below the bar for even thinking about in such a project.  Can you document a single example where this exploit vector has been used in any project?

In any case, I don't think security is a high priority in scientific projects.  Can you describe a scenario where an exploit in Elemental itself would have a material impact on someone?

**Comment by elfring** [comment]
* Would you like to support the use case that your header files should occasionally only be found from the installed system directories?
* How often will it matter that the mentioned "current directory" will usually be different from search paths specified by arguments like "`-I`"?

**Comment by justusc** [comment]
> * Would you like to support the use case that your header files should occasionally only be found from the installed system directories?
> * How often will it matter that the mentioned "current directory" will usually be different from search paths specified by arguments like "-I"?

Do you have a use case where you can show that file search time is a problem? If not, these are all non-issues. File search is very fast.

**Comment by elfring** [comment]
* I guess that compilation time differences can eventually become also interesting.
* But I find it more important to be reasonably sure that the desired computations were really correct because it could be determined by the applied software build parameters that the used functions were actually derived from the expected source files. Can you follow this design concern?

**Comment by poulson** [comment]
Compilation times are indeed an issue but are unrelated to this issue, which I see you have posted with identical wording in other locations: https://github.com/elfring?tab=activity Furthermore, I am convinced your responses are scripted due to you posting identical comments in multiple locations. Your other issue for Elemental is valid, but this one is not, as the user is the one that controls the directories which are searched.

**Comment by elfring** [comment]
My responses are not scripted so far. I can understand that it might appear to you so while I dare to repeat some update suggestions at various places.
I imagine that the amount of control of "the user" about the software build environment can become another interesting topic for further considerations, can't it?

**Comment by poulson** [comment]
I have blocked elfring from Elemental.

**Comment by jedbrown** [comment]
FWIW, PETSc switched from mostly `""` includes to consistent `<>` includes in 2011 because correctness had always depended on the `""` search failing and falling back to `<>` semantics. It is slightly lower cognitive load for a reader unfamiliar with the intended semantics because they don't need to check that no such header exists in the same directory as the source file. It is a very minor issue and a distraction to discuss at length, but I would not reject a pull request that made this change. I would have simply replied "patches welcome".
