### ISSUE TITLE
Support of full SVD

### ISSUE THREAD

**Issue by icfy** [elemental/Elemental#125]
Currently Elemental supports thin SVD if A in SVD(A, s, V) is thin(m-by-n, and m > n), where the counterpart Matlab function [U, S, V] = svd(X) would return full U(m-by-m) even if the input X is thin(m-by-n, and m > n). 
Supporting this function is a great help when many scientific computing programs are written in matlab while in need of translating into Elemental.

**Comment by poulson** [comment]
The following commit made partial progress by lifting the SVD interface up to what will be needed for supporting a 'full' SVD: `SVD( A, U, s, V, ctrl )` as opposed to `SVD( A, s, V, ctrl )`, where Elemental used to overwrite `A` with `U`. Clearly the latter is not possible if A is taller than it is wide and a full SVD is requested.

**Comment by poulson** [comment]
Support for 'compact' SVD's is now enabled via https://github.com/elemental/Elemental/commit/bdb761aaef0aa877429c449c7fbae802f5201c87

Support for full SVD's (as well as `Image` and `Kernel` routines) should be forthcoming.

**Comment by poulson** [comment]
@icfy As of the following commit, https://github.com/elemental/Elemental/commit/0501069f77bcc1261908c61cb877a28320d203dc, Elemental supports the `FULL_SVD`, `THIN_SVD`, `COMPACT_SVD`, and `THRESHOLDED_SVD` options with the syntax `SVD( A, U, s, V, ctrl )` and `SVD( A, s, ctrl )`, where neither modified the matrix `A` unless `ctrl.overwrite = true` was specified.

**Comment by poulson** [comment]
@icfy `THRESHOLDED_SVD` has been renamed to `PRODUCT_SVD` since its purpose was otherwise easily confused with that of `COMPACT_SVD`. 

Using the new names, `COMPACT_SVD` returns the singular triplets with singular values greater than or equal to (by default) `Max(m,n)*eps*TwoNorm(A)`, whereas `PRODUCT_SVD` explicitly forms `A^H * A`, computes the eigenvalues with magnitude at least (by default) `Max(m,n)*Sqrt(eps)*TwoNorm(A^H*A)`, say `V`, and then forms the left singular vectors as `U := A V / Sigma` (which tends to lead to the columns of `U` not being very orthonormal if the tolerance was too small). Some sort of iterative refinement should likely be introduced to improve the accuracy of this approach (perhaps in the same manner as employed by Yuji Nakasukasa and Nicholas Higham for their QWDH-based SVD).

**Comment by icfy** [comment]
Thank you so much!
Should I close this issue now?

**Comment by poulson** [comment]
I would wait until you verify that it works for your purpose.

**Comment by poulson** [comment]
I'd also like to finish adding `Kernel`, `Image`, and `KernelAndImage` routines before closing since they are of the same ilk.

**Comment by icfy** [comment]
I've just tested, and it's perfect for my work! 
Again, thanks a lot.

**Comment by poulson** [comment]
There are now (https://github.com/elemental/Elemental/commit/295fdaadcdaba740dfa04ab1eed45c19f79b774a) `Image`, `Kernel`, and `ImageAndKernel` routines which make use of the new `SVD` control options. Additional control structure members (`avoidComputingU` and `avoidComputingV`) were added for cases where only the left or right singular vectors are needed (e.g., within `Image` and `Kernel`), but they are not yet exploited within `SVD`.

**Comment by poulson** [comment]
As of this commit (https://github.com/elemental/Elemental/commit/a7d3d608367bf0382f79ddae721db83c284c8359), Elemental's SVD supports optionally avoiding the computation of either `U` or `V` and this has been exploited within the routines `ImageAndKernel`, `Image`, and `Kernel`, which now have the example driver `examples/lapack_like/ImageAndKernel.cpp`
