### ISSUE TITLE
Make a Release Of Elemental

### ISSUE THREAD

**Issue by rhl-** [elemental/Elemental#172]
Lets use this issue to track the issue of making a release of elemental

Lets compose a list of what needs to be done to release the next Elemental.
- Decide on a release version number
- Update website

**Comment by rhl-** [comment]
Per gitter conversation the next version will be 0.87

**Comment by haimav** [comment]
Are there still plans to have an official release of Elemental? The last release is over 2 years old, and very outdated.

**Comment by poulson** [comment]
Yep. I'm actively working on adding an Elemental implementation of a distributed Hessenberg QR algorithm so that packaging will not require ScaLAPACK as a dependency to have full library support (and, additionally, to provide more general datatype support for the distributed eigensolvers). It's a thankless task but is worth doing.

**Comment by haimav** [comment]
You will definitely have my thanks, so it is not thankless ;-)

**Comment by rhl-** [comment]
https://github.com/elemental/Elemental/releases/tag/v0.87
