### ISSUE TITLE
CMakeLists:PYTHON_SITE_PACKAGES logic incorrect

### ISSUE THREAD

**Issue by jiahao** [elemental/Elemental#44]
1. CMake does not correctly ignore `PYTHON_SITE_PACKAGES` when `INSTALL_PYTHON_PACKAGE=OFF` ; when doing `make install`, it will still attempt to build and install the Python package to `PYTHON_SITE_PACKAGES`. Erasing `PYTHON_SITE_PACKAGES` avoided this issue.

2. CMake does not check that the current user has write permissions to `PYTHON_SITE_PACKAGES`, thus causing the build to fail during `make install` for users who do not have write permissions to the systemwide `PYTHON_SITE_PACKAGES`. Instead, it may be more sensible to detect for write permissions, falling back to [installing at the user level](https://docs.python.org/2/install/#alternate-installation-the-user-scheme) instead.

**Comment by poulson** [comment]
I believe that (1) was introduced during yesterday's commit that avoids python 3. I have committed what should be a fix here:         https://github.com/elemental/Elemental/commit/6c0bf8e22cb104d20df820b8af2023a1aa0118b0

**Comment by jiahao** [comment]
thanks!

**Comment by poulson** [comment]
Closing due to consensus with @jakebolewski and @jiahao that we're approaching over-engineering for the current python installation mechanism; ideally the python package will be separated from elemental for release versions of the library. Thus, the current development installation interface should be sufficient.
