### ISSUE TITLE
Moving away from git submodules

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#52]
It appears (thanks to @horrovac) that GitHub does not include submodules within its autogenerated zip and tarballs, and so users which download these will suffer through a long pointless and confusing failing build process. And it is apparently impossible to disable GitHub generating these download links. Furthermore, git submodules confuse users who did not read the instructions that Elemental should be recursively cloned (i.e., with ``git clone --recursive`` rather than just ``git clone``).

For this reason, it might be worthwhile to switch to git subtrees. I'm not very familiar with them, but it would appear that this is the standard solution to the above issues. I consider this a high priority.

**Comment by justusc** [comment]
Another possible solution is to use CMake's External Project module. It nicely wraps the download, configure, build, and install process for external projects. Incidentally, this is how I include Elemental in my TiledArray project. The advantage of this approach is that users can use existing installations of the external projects or let CMake handle it. This of course requires extra work in the configure scripts.

See the following link for more details. http://www.cmake.org/cmake/help/v3.0/module/ExternalProject.html

I have also used Subtrees to include Elemental in MADNESS. The process is fairly easy if you only plan to pull up stream changes, and do not anticipate modifing the code of the external project.

**Comment by jeffhammond** [comment]
I agree with @justusc .  That's one nice feature of CMake and I think it's less disruptive, provided that the subprojects are not breaking API compatibility quickly and you can let CMake download a release tarball somewhere.  It pretty much defeats the purpose if CMake ends up doing a git clone...

**Comment by justusc** [comment]
In my experience, Git clone and tarball download work equally well with CMake's External Project, which handles both cases. The caveat with git/hg/svn clone is that you typically want to hard code it to download a particular revision or tag to avoid interface breakage and other compatibility issues. This is of  course equivalent to downloading a fixed tarball.

**Comment by poulson** [comment]
@justusc @jeffhammond These are great points. I'll look into having git clone's through CMake External projects for development versions and tarball downloads for release versions.

**Comment by rhl-** [comment]
ExternalProject_add is a nice tool, but, it does have one quirk. If you include it directly in CMake the target it creates can re-execute more than "just once." I just developed this for myself in my applied topology library [CTL](https://github.com/appliedtopology/ctl). Since you are bringing up the topic I will share how I implemented my dependency system.

The way I implemented the dependency finding (which is not perfect) was to create a `external/DEP_NAME_HERE` directory and then have a whole separate CMake project just to add the one example. Since I also use METIS, here is how I did that:
[CTL: METIS ExternalProject_add](https://github.com/appliedtopology/ctl/blob/master/dependencies/external/metis/CMakeLists.txt)

I also chose to make dependencies install in the users home directory by default..

And, in addition, I also provide a way that the user may specify alternative installation directories via [build_dependencies.txt](https://github.com/appliedtopology/ctl/blob/master/build_dependencies.txt)

CMake then:
 1. Checks for user provided info, and uses that if provided
 2. sets up calls to the `find_package()` routine
See that here:
[CTL: METIS find_package()] (https://github.com/appliedtopology/ctl/blob/master/dependencies/CMakeLists.txt#L99)

Within CMake I then added these convience wrappers: 
`add_custom_target(metis COMMAND cmake . -DMetis_Version=${Metis_Version} COMMAND make WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/dependencies/external/metis)`

As well as:

`add_custom_target(dependencies)`
`add_dependencies(dependencies ann boost metis tbb)`

Also happy to accept criticism of this, since I don't think it's perfect, but, decent.

**Comment by jeffhammond** [comment]
@justusc For me, the point of the download feature is to not require the user to have version control software installed on their system.  I have had users of ARMCI-MPI complain to me that they cannot use it because the documented way to install it starts with Git.  Granted, CMake isn't always installed by default, but it's a reasonable dependency for building a library; arguably, Git is not.

**Comment by jedbrown** [comment]
Note that many of those machines with a "reason" for not having Git will also lack internet access.

**Comment by jeffhammond** [comment]
@jedbrown Fortunately, such people also lack email to complain about their problem :-)  Anyways, this is not my experience.  Plenty of application users do not have version control installed on their workstations or clusters but merely want to wget/curl a bunch of tarballs and build them.  I used NWChem for many years before I ever installed Git on my machine...

**Comment by poulson** [comment]
There are now no more submodules: https://github.com/elemental/Elemental/commit/21d673c38cf53f97e2d45922531455bce86f153e
Hopefully I can add ParMETIS support back in soon with a warning that ParMETIS cannot be used commercially.
