### ISSUE TITLE
Build against exernal METIS lib?

### ISSUE THREAD

**Issue by dpo** [elemental/Elemental#55]
I didn't see a CMake option to build against an external METIS library? Same question about ParMETIS.

Thanks.

**Comment by poulson** [comment]
The build system is currently being modified since GitHub seems to be fundamentally incompatible with git submodules, but, for now, you should be able to set METIS_ROOT to the METIS installation directory, METIS_LIBS to the METIS libraries, and BUILD_METIS=OFF to tell Elemental to look elsewhere.

As for ParMETIS: support used to be enabled but was disabled due to ParMETIS's license not allowing for commercial usage. If this is important to you, it would be possible to create a branch which supports ParMETIS.

**Comment by dpo** [comment]
Thanks. Actually I found that I had to set `BUILD_METIS=OFF`, `MANUAL_METIS=ON` along with `METIS_ROOT` and `METIS_LIBS`, but Elemental looks for `libmetis.h`, which is part of the METIS source tree, but isn't installed.

I'm happy to leave ParMETIS where it is for now.

**Comment by poulson** [comment]
Thanks for letting me know; that is a bit ridiculous and I'll try to fix it.

**Comment by poulson** [comment]
It should now be possible to build against an external METIS build: https://github.com/elemental/Elemental/commit/21d673c38cf53f97e2d45922531455bce86f153e

**Comment by poulson** [comment]
Support for ParMETIS is now enabled: https://github.com/elemental/Elemental/commit/a617eea288e9e8c388b93f4312592239cfc48221

**Comment by dpo** [comment]
Many thanks. I presume those will be part of the next release?

**Comment by poulson** [comment]
Yes, it's in the dev version and I'm trying my best to get the docs updated and to push it out. But this process sometimes feels more like a treadmill than anything else.

**Comment by dpo** [comment]
Trying to link `master` against my ParMETIS, I'm getting
````
 CMake Warning at external/cmake/parmetis.cmake:18 (message):
   ParMETIS was found, but parmetislib.h was not, and so ParMETIS must be
   built again to allow for a custom parallel vertex separation routine to be
   built
````
`parmetislib.h` is part of the source tree but isn't installed by ParMETIS (same as METIS). Is it really required? If so, I'll change the Homebrew formula for `parmetis` to install it.

ps: I'm also getting
````
 CMake Warning at CMakeLists.txt:216 (message):
   Build mode not specified, defaulting to Release build.
````
although I specified `CMAKE_BUILD_TYPE`. I don't see any `CMAKE_BUILD_MODE` in the list.

**Comment by poulson** [comment]
@dpo Elemental only interacts with METIS and ParMETIS through routines which perform nodal bisection (METIS calls them vertex separators), and, while METIS provides an undocumented "vertex separator" routine, ParMETIS does not. For this reason, Elemental makes use of ParMETIS's internal APIs (in particular, parmetislib.h) in order to build a parallel vertex separation routine.

As for the ``CMAKE_BUILD_TYPE``, the new build types are simply ``Debug`` and ``Release`` in order to conform to standards better, and there is now an option ``EL_HYBRID`` which defaults to ``OFF``.

**Comment by dpo** [comment]
I couldn't get Elemental to build against an external ParMETIS even if I manually install `parmetislib.h`. The latter includes `GKlib.h`, which is found under `metis/GKlib` in both METIS and ParMETIS and is (a) not installed either, and (b) anyways, that location is never in the list of include dirs. It's really too bad METIS and ParMETIS aren't dissociated.

**Comment by poulson** [comment]
Yes, it would require a bit of work to install an external ParMETIS. Is this important for you?

**Comment by dpo** [comment]
It's just that it makes sense in a package manager like Homebrew to indicate ParMETIS as a dependency. I've already dissociated METIS from ParMETIS, but that was a hack, not a feature: https://github.com/Homebrew/homebrew-science/blob/master/parmetis.rb#L40

**Comment by poulson** [comment]
It would be easy to modify the CMakeLists.txt from a fork of ParMETIS to install the necessary headers. Perhaps this is the way to allow for an external dependency?

**Comment by dpo** [comment]
At least in the homebrew formula, I can install the headers easily. The problem is more with the way they include one another, I feel. For instance, `parmetislib.h` has this line
````
include "GKlib.h"
````
In the source tree, `GKlib.h` is found under `metis/GKlib`. (In the METIS source tree, it's found under `GKlib`). We could just patch `parmetislib.h` so the line above reads
````
include "GKlib/GKlib.h"
````
and install `GKlib` to the METIS `include` dir. And do something similar with the others.

Of course the more robust way would be to convince George to install those headers by default in a way that makes it possible for other packages to use them.

**Comment by poulson** [comment]
For now, I would simply extend the ParMETIS installation candidate list and modify Homebrew to search the extra directory. The latency of the upstream change request is likely be significant. 

And, beyond that, it's my opinion that the right way forward is to create a standard fork of METIS and ParMETIS. PETSc has similar concerns about interoperability with METIS/ParMETIS. @jedbrown
